services:
  playwright-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: playwright-cookie-service
    ports:
      - '8000:8000'
    volumes:
      - ./logs:/app/logs
    environment:
      - PYTHONUNBUFFERED=1
      - DEV_MODE=${DEV_MODE}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
    restart: unless-stopped
